node {
	def app
	stage('Build Docker Image') {
		checkout scm
		app = docker.build('dockerhp/sample-app:latest')
	}
	
	stage('Publish to docker HUb') {
		docker.withRegistry("https://index.docker.io/v1/", "dockerhub") {
			app.push('latest')
		}
	}
	
	stage('deploy to production') {
		docker.withServer('tcp://production:2376', 'production') {
			sh 'docker run -d dockerhp/sample-app'
		}
	}
} 
